// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yadcdvyzfnhjzognvqtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZGNkdnl6Zm5oanpvZ252cXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzQyMTAsImV4cCI6MjA1OTk1MDIxMH0.pbNQyJK5MVDx6hoCnyfu9tpeXRDzbqnl4qNRXiO656Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);